from django.urls import path

from . import views

app_name = "hive"
urlpatterns = [
    path("", views.root_view, name="root"),
    path("setup", views.SetupView.as_view(), name="setup"),
    path('hive_configure/', views.hive_configure, name='hive_configure'),
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("connection_status", views.connection_status, name="connection_status"),
    path("live_activity/<int:pk>", views.live_activity, name="live_activity"),
    path("monitor/<int:pk>", views.LiveMonitorView.as_view(), name="monitor"),
    path("transcripts/<int:pk>", views.TranscriptView.as_view(), name="transcripts"),
    path("transcript_download/<int:pk>/<str:day>", views.transcript_download, name="transcript_download"),
    path("test_ai_connection", views.test_ai_connection, name="test_ai_connection"),
    path('dashboard/<str:alert_message>/', views.DashboardView.as_view(), name='dashboard_alert'),
    path("interact/<int:pk>", views.InteractionView.as_view(), name="interact"),
    path("interact_update", views.interact_update, name="interact_update"),
    path("reload_database", views.reload_database, name="reload_database"),
    path('endpoint/', views.endpoint_qr, name='endpoint_qr'),
    path('wifi_edit/', views.WifiQREditView.as_view(), name='wifi_edit'),
    path('wifi_qr/', views.wifi_qr, name='wifi_qr'),
    path("moxie/<int:pk>", views.MoxieView.as_view(), name="moxie"),
    path("moxie_data/<int:pk>", views.MoxieDataView.as_view(), name="moxie_data"),
    path("moxie_missions/<int:pk>", views.MoxieMissionsView.as_view(), name="moxie_missions"),
    path("mission_edit/<int:pk>", views.mission_edit, name="mission_edit"),
    path("face/<int:pk>", views.MoxieFaceView.as_view(), name="face"),
    path("face_edit/<int:pk>", views.face_edit, name="face_edit"),
    path("moxie_edit/<int:pk>", views.moxie_edit, name="moxie_edit"),
    path("moxie_wake/<int:pk>", views.moxie_wake, name="moxie_wake"),
    path("moxie_wake_chat/<int:pk>", views.moxie_wake_chat, name="moxie_wake_chat"),
    path("moxie_launcher/<int:pk>", views.MoxieLauncherView.as_view(), name="moxie_launcher"),
    path("trivia_settings/<int:pk>", views.TriviaSettingsView.as_view(), name="trivia_settings"),
    path("trivia_configure/<int:pk>", views.trivia_configure, name="trivia_configure"),
    path("launch_mission/<int:pk>", views.launch_mission, name="launch_mission"),
    path("clear_conversation_memory/<int:pk>", views.clear_conversation_memory, name="clear_conversation_memory"),
    path("robot_control/<int:pk>", views.robot_control, name="robot_control"),
    path("puppet/<int:pk>", views.MoxiePuppetView.as_view(), name="puppet"),
    path("puppet_api/<int:pk>", views.puppet_api, name="puppet_api"),
    path("export_content/", views.ExportDataView.as_view(), name="export_content"),
    path("export_data/", views.export_data, name="export_data"),
    path("import_review/", views.upload_import_data, name="import_review"),
    path("import_data/", views.import_data, name="import_data"),
]
