"""
Django settings for openmoxie project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import secrets
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_STORE_DIR = BASE_DIR / 'work'
# Logging is configured while Django imports settings, before migrations or the
# application get a chance to create the persistent work directory.
DATA_STORE_DIR.mkdir(parents=True, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

def _local_secret_key():
    """Keep each family's signing key in private runtime storage, not Git."""
    key_file = DATA_STORE_DIR / '.django-secret-key'
    if key_file.exists():
        return key_file.read_text(encoding='utf-8').strip()
    key = secrets.token_urlsafe(64)
    key_file.write_text(key, encoding='utf-8')
    return key


SECRET_KEY = os.environ.get('OPENMOXIE_SECRET_KEY') or _local_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('OPENMOXIE_DEBUG', '').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [item.strip() for item in os.environ.get('OPENMOXIE_ALLOWED_HOSTS', '*').split(',') if item.strip()]


# Application definition

INSTALLED_APPS = [
    'hive.apps.HiveConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'jquery',
    'django_bootstrap5'
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'collected_static'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'openmoxie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'openmoxie.version_context.moxie_version',
            ],
        },
    },
]

INTERNAL_IPS = [
    # ...
    "0.0.0.0",
    # ...
]

WSGI_APPLICATION = 'openmoxie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_STORE_DIR / 'db.sqlite3',
        # MQTT callbacks and dashboard requests write from different threads.
        # Wait for short-lived writers and acquire the write lock at BEGIN so a
        # read-then-write transaction cannot fail immediately during upgrade.
        'OPTIONS': {
            'timeout': 10,
            'transaction_mode': 'IMMEDIATE',
        },
    }
}

MQTT_ENDPOINT = {
    'host': 'mqtt',
    'port': 8883,
    'project': 'openmoxie',
    'cert_required': False,
}

BOOTSTRAP5 = {
    'css': {
        'url': '/static/bootstrap/css/bootstrap.min.css'
    },
    'js': {
        'url': '/static/bootstrap/js/bootstrap.min.js'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime:15} {levelname} [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message} ({module}:{lineno})',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': DATA_STORE_DIR / 'debug.log',
            'when': 'D',  # Daily rotation
            'interval': 1,  # Rotate every 1 day
            'backupCount': 30,  # Keep 30 days
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'hive': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
